### ISSUE TITLE
Doesn't compile on latest Rust version, missing lifetime specifier

### ISSUE THREAD

**Issue by BillyDM** [pdeljanov/Symphonia#408]
Symphonia fails to compile on the latest stable version of Rust. It gives the error message:

```
   Compiling symphonia v0.5.4
error[E0106]: missing lifetime specifier
   --> /home/billydm/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/symphonia-0.5.4/src/lib.rs:219:28
    |
219 |     pub fn get_codecs() -> &CodecRegistry {
    |                            ^ expected named lifetime parameter
    |
    = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime, but this is uncommon unless you're returning a borrowed value from a `const` or a `static`
    |
219 |     pub fn get_codecs() -> &'static CodecRegistry {
    |                             +++++++
help: instead, you are more likely to want to return an owned value
    |
219 -     pub fn get_codecs() -> &CodecRegistry {
219 +     pub fn get_codecs() -> CodecRegistry {
    |

For more information about this error, try `rustc --explain E0106`.
error: could not compile `symphonia` (lib) due to 1 previous error
```

**Comment by pdeljanov** [comment]
Rust 1.90 seems to build Symphonia fine on the `v0.5.4` tag on my end. Albeit with many warnings. I'll cut a new release since `master` builds clean, but would be interested in knowing how to repro the build issue.

**Comment by BillyDM** [comment]
Ok yeah, I can confirm that the `master` branch builds fine.

**Comment by BillyDM** [comment]
So yeah, all you need to do to reproduce the issue is to add `symphonia = "0.5.4"` as a dependency in another crate.

**Comment by pdeljanov** [comment]
Hmm, I created a new binary crate (not part of the existing Symphonia repository), added `symphonia = 0.5.4` to it, and copied the getting started sample into `main.rs` and it still builds and runs fine with stable and nightly. Perhaps you have some additional compiler settings?

I'm glad to hear that `master` works fine, though.

**Comment by pdeljanov** [comment]
FYI, I just published v0.5.5 on crates.io.

**Comment by edwloef** [comment]
I'm also not able to reproduce this with `0.5.4` or `0.5.5`, both work fine on my end. Looking at the docs, the lifetime specifier is also there. Maybe you've accidentally corrupted your local registry?

**Comment by BillyDM** [comment]
Thanks! Version is `0.5.5` is working!

**Comment by BillyDM** [comment]
> I'm also not able to reproduce this with `0.5.4` or `0.5.5`, both work fine on my end. Looking at the docs, the lifetime specifier is also there. Maybe you've accidentally corrupted your local registry?

Hmm, I tried `cargo clean` for version `0.5.4`, but that didn't fix it.

**Comment by edwloef** [comment]
You'll need to delete `~/.cargo/registry` to clear things out. `cargo-cache` can also do it for you via `cargo cache -r all`.

**Comment by BillyDM** [comment]
> You'll need to delete `~/.cargo/registry` to clear things out. `cargo-cache` can also do it for you via `cargo cache -r all`.

Oh, that was the issue! Weird, of all the years I've worked with Rust I've never had a corrupted local registry. Well, good to know!
